### ISSUE TITLE
More properties and dynamically load them in

### ISSUE THREAD

**Issue by gShahr** [Modular-Robotics-Group/modular-robotics#72]

**Comment by Clementsaic** [comment]
Runtime property linking should be set up now, as of https://github.com/gShahr/modular-robotics/commit/2506c7bd284fe728f0dcb87caeb4d5fbfaabbfdd it appears to be working as intended. The process of creating properties will definitely need some documentation and fine-tuning before we add any more properties though.

**Comment by Clementsaic** [comment]
Orientation property was added, which proves the feasibility of linking multiple properties at runtime and having certain properties be modified by moves.
